/**
 * Downloads every photo in photos.manifest.mjs from Unsplash, resizes it into
 * public/photos/<key>.jpg, and writes lib/photos.ts with dimensions, a tiny
 * blur placeholder and the photographer's name (for /credits).
 *
 *   npm run photos            fetch anything missing
 *   npm run photos -- --force re-fetch everything
 */
import fs from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";
import { manifest } from "./photos.manifest.mjs";

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, "$1")), "..");
const outDir = path.join(root, "public", "photos");
const cacheFile = path.join(root, "scripts", ".photo-cache.json");
const force = process.argv.includes("--force");

await fs.mkdir(outDir, { recursive: true });
const cache = JSON.parse(await fs.readFile(cacheFile, "utf8").catch(() => "{}"));

/** "tommaso-ubezio-UA0p9yPn-QQ-unsplash.jpg" → "Tommaso Ubezio" */
function photographerFrom(url, id) {
  const dl = new URL(url).searchParams.get("dl") ?? "";
  const slug = dl.replace(`-${id}-unsplash.jpg`, "");
  return slug
    .split("-")
    .filter(Boolean)
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join(" ");
}

async function fetchOne(item) {
  const file = path.join(outDir, `${item.key}.jpg`);
  const have = await fs.stat(file).then(() => true, () => false);
  if (have && cache[item.key] && !force) return cache[item.key];

  const res = await fetch(`https://unsplash.com/photos/${item.id}/download?force=true&w=${item.width}`, {
    headers: { "User-Agent": "Mozilla/5.0 (concept-site photo fetch)" },
    redirect: "follow",
  });
  if (!res.ok) throw new Error(`${item.key} (${item.id}): HTTP ${res.status}`);
  const buffer = Buffer.from(await res.arrayBuffer());

  const image = sharp(buffer).rotate().resize({ width: item.width, height: item.width, fit: "inside", withoutEnlargement: true });
  const { data, info } = await image.jpeg({ quality: 82, mozjpeg: true, progressive: true }).toBuffer({ resolveWithObject: true });
  await fs.writeFile(file, data);

  const blur = await sharp(data).resize(16, 16, { fit: "inside" }).jpeg({ quality: 60 }).toBuffer();
  const entry = {
    width: info.width,
    height: info.height,
    blur: `data:image/jpeg;base64,${blur.toString("base64")}`,
    photographer: photographerFrom(res.url, item.id),
  };
  cache[item.key] = entry;
  console.log(`✓ ${item.key.padEnd(18)} ${info.width}×${info.height}  ${(data.length / 1024).toFixed(0)} KB  — ${entry.photographer}`);
  return entry;
}

const results = [];
for (let i = 0; i < manifest.length; i += 6) {
  const batch = manifest.slice(i, i + 6);
  results.push(...(await Promise.all(batch.map(fetchOne))));
}
await fs.writeFile(cacheFile, JSON.stringify(cache, null, 2));

const lines = manifest.map((item, i) => {
  const r = results[i];
  return `  ${item.key}: { src: "/photos/${item.key}.jpg", width: ${r.width}, height: ${r.height}, alt: ${JSON.stringify(item.alt)}, blurDataURL: "${r.blur}", credit: { name: ${JSON.stringify(r.photographer)}, url: "https://unsplash.com/photos/${item.id}" } },`;
});

await fs.writeFile(
  path.join(root, "lib", "photos.ts"),
  `/* Generated by scripts/fetch-photos.mjs — edit photos.manifest.mjs, then run \`npm run photos\`. */

export type Photo = {
  src: string;
  width: number;
  height: number;
  alt: string;
  blurDataURL: string;
  credit: { name: string; url: string };
};

export const photos = {
${lines.join("\n")}
} satisfies Record<string, Photo>;

export type PhotoKey = keyof typeof photos;
`,
);
console.log(`\nWrote ${manifest.length} photos and lib/photos.ts`);
